export const itemList = [
    "Decyl Glucoside",
    "Alkyl (c8,c10) Polyglycoside",
    "APG0810",
    "(C8-10) Alkyl ether of corn sugar",
    "C16H32O6",
    "D-Glucopyranoside, decyl",
    "D-Glucopyranose, Oligomeric, Decyl Octyl Glycosides",
    "D-glucose, decyl octyl ethers, oligomeric",
    "Decyl D-glucopyranoside",
    "Decyl D-glucoside",
    "Decyl octyl d-glucose",
    "Glucoside, decyl",
    "Fragrance Mix 2",
    "Hexyl cinnamic aldehyde (Article Number H-025", 
    "Coumarin (Article Number C-038)", 
    "Farnesol (Article Number F-004)", 
    "Hydroxyisohexyl 3 Cyclohexene Carboxaldehyde (Article Number L-003)",
    "Citral (Article Number C-036)",
    "Citronellol (Article Number C-037)",
    "Fragrance Mix 1",
    "Amyl Cinnamal (Article Number A-014)",
    "Cinnamyl Alcohol (Article Number C-013)",
    "Cinnamal (Article Number C-014)",
    "Eugeno (Article Number E-016)",
    "Geraniol (Article Number G-001)",
    "Hydroxycitronellal (Article Number H-008)",
    "Isoeugenol (Article Number I-002)",
    "Oakmoss Absolute (Article Number O-001)",
    "Methyldibromoglutaronitrile (MDBGN)",
    "1,2-Dibromo-2,4-dicyanobutane",
    "2-Bromo-2 (bromomethyl) glutaronitrile",
    "2-Bromo-2 (bromomethyl) pentanedinitrile",
    "BBMG",
    "Dibromodicyanobutane",
    "Merquat 2200",
    "Metacide 38",
    "Tektamer 38",
    "Tuopai DM",
    "16, 16-Butylidenebis(oxy)-11,21-dihydroxypregna-1,4-diene-3,20-dione",
    "(R,S)-11b-16a,17,21,tetrahydroxypregna-1,4-diene-3,20-dione cyclic 16,17-acetal with buturaldehyde",
    "Budenoside",
    "Budeson",
    "Preferid",
    "Pulmicort",
    "Pregna-1,4-diene-3,20-dione,16,17-(butylidenebis(oxy))-11,21-dihydroxy-1,(11beta,16alpha)",
    "Rhincort", 
    "S-1320",
    "Spirocort",
    "Triamcinolone acetonide"
  ];